#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Std qw( getopts );

use FindBin qw( $RealBin );
use lib "$RealBin/lib";

my %opts;
getopts( 'sh:p:U:P:', \%opts );

my $command = shift;
eval "use $command";
if ( $@ ) {
  die $@;
}

my $subcommand = "$command"->new( \%opts );
if ( defined $subcommand ) {
  $subcommand->execute( @ARGV );
}

exit 0;
